In [2]:
import pandas as pd

In [ ]:
# pandas has two core object series,  dataframe. Series is a one-dimensional array, and dataframe is a two-dimensional array.

In [3]:
#series

pd.Series((1,2,3,4,5))  # Output: 0    1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [18]:
# dataframe
#dictionary of series
di={"name": ["shaurya","mango","pen", "mobile"],
    "identity": ["human","fruit","stationary","electronic"]
}
df=pd.DataFrame(di)

In [19]:
print(type(df))

<class 'pandas.DataFrame'>

In [20]:
df.head(2)

      name identity
0  shaurya    human
1    mango    fruit

In [22]:
df.tail(2)

     name    identity
2     pen  stationary
3  mobile  electronic

In [23]:
df.sample(2)

     name    identity
3  mobile  electronic
2     pen  stationary

In [24]:
df.head()

      name    identity
0  shaurya       human
1    mango       fruit
2      pen  stationary
3   mobile  electronic

In [25]:
count=[1,10,3,2]
df.insert(0,"count",count)

In [26]:
df

   count     name    identity
0      1  shaurya       human
1     10    mango       fruit
2      3      pen  stationary
3      2   mobile  electronic

In [27]:
colour = "skin","orange","blue","black"

In [28]:
df[colour] =colour

In [29]:
df["id"] = [1,2,3,4]

In [30]:
df.sample()

   count    name    identity (skin, orange, blue, black)  id
3      2  mobile  electronic                       black   4

In [31]:
# new dataframe df2 id, weight
df2 = pd.DataFrame({"id":[1,2,6,4,5],
"weight":[50,60,70,80,None ]})

print(df2)

   id  weight
0   1    50.0
1   2    60.0
2   6    70.0
3   4    80.0
4   5     NaN

In [ ]:
#merge  or join
pd.merge(df,df2, how="right" , on="id")

   count     name    identity (skin, orange, blue, black)  id  weight
0    1.0  shaurya       human                        skin   1    50.0
1   10.0    mango       fruit                      orange   2    60.0
2    NaN      NaN         NaN                         NaN   6    70.0
3    2.0   mobile  electronic                       black   4    80.0
4    NaN      NaN         NaN                         NaN   5     NaN